const fields = [
  "wallbang",
  "graffiti at enemy spawn",
  "5 bombs planted or defused",
  ">50% headshot rate",
  "10 assists",
  ">20 enemies flashed",
  "top fragger",
  "10 kills on ct side",
  "ace",
  ">200 utility damage",
  "knife kill",
  "kill while flashed",
  "no scope kill",
  "2 kills with negev",
  "2 kills with grenades",
  "kill through a smoke",
  "10 kills on t side",
  "kill with a zeus",
  ">69 ADR",
  "bottom fragger",
  "5 kills with an enemy weapon",
  "3 MVP stars",
  "win a clutch (1vs.X)",
  "AK 3K",
  "M4 3K",
  "5 kills with Famas",
  "5 kills with galil",
  "5 kills with pistol",
  "2 kills with shotgun",
  "12 rounds lost",
  "suicide"
];
export default fields;
