const fields = [
  "kill through wall",
  "graffiti enemy spawn",
  "5 bomb plant/defuse",
  ">50% HS",
  "10 assist",
  ">20 enemie flashed",
  "top fragger",
  "10 kill ct side",
  "ace",
  ">200 utility damage",
  "kill with knife",
  "kill while flashed",
  "kill while noscope",
  "2 kill with negev",
  "2 kill with grenade",
  "kill through smoke",
  "10 kill t side",
  "kill with zeus",
  ">69 ADR",
  "bottom fragger",
  "5 kill with enemy weapon",
  "3 MVP",
  "clutch (1vs.X)",
  "AK 3K",
  "M4 3K",
  "5 kill with Famas",
  "5 kill with galil",
  "5 kill with pistol",
  "2 kill with shotgun",
  "12 round lost",
  "suicide"
];
export default fields;
